In [1]:
import pandas as pd

In [6]:
muslim = {
    'country': ['bangladesh', 'pakistan', 'egypt', 'indonesia'],
    'capital': ['dhaka', 'islamabad', 'cairo', 'jakarta'],
    'area': [0.148, 0.882, 1.001, 1.905],
    'population': [170, 240, 112, 277]
}

In [7]:
muslim

{'country': ['bangladesh', 'pakistan', 'egypt', 'indonesia'],
 'capital': ['dhaka', 'islamabad', 'cairo', 'jakarta'],
 'area': [0.148, 0.882, 1.001, 1.905],
 'population': [170, 240, 112, 277]}

In [8]:
df = pd.DataFrame(muslim)

In [9]:
df

      country    capital   area  population
0  bangladesh      dhaka  0.148         170
1    pakistan  islamabad  0.882         240
2       egypt      cairo  1.001         112
3   indonesia    jakarta  1.905         277

In [33]:
area = df['area'] > 1

In [34]:
area

0    False
1    False
2     True
3     True
Name: area, dtype: bool

In [35]:
df[area]

     country  capital   area  population
2      egypt    cairo  1.001         112
3  indonesia  jakarta  1.905         277