In [ ]:
import pandas as pd

In [ ]:
muslim = {
    'country': ['bangladesh', 'pakistan', 'egypt', 'indonesia'],
    'capital': ['dhaka', 'islamabad', 'cairo', 'jakarta'],
    'area': [147570, 881913, 1001450, 1904569],
    'population': [170, 240, 112, 277]
}

In [ ]:
muslim

{'country': ['bangladesh', 'pakistan', 'egypt', 'indonesia'],
 'capital': ['dhaka', 'islamabad', 'cairo', 'jakarta'],
 'area': [147570, 881913, 1001450, 1904569],
 'population': [170, 240, 112, 277]}

In [ ]:
type(muslim)

dict

In [ ]:
df = pd.DataFrame(muslim)

In [ ]:
df

      country    capital     area  population
0  bangladesh      dhaka   147570         170
1    pakistan  islamabad   881913         240
2       egypt      cairo  1001450         112
3   indonesia    jakarta  1904569         277

In [ ]:
df.index = ['ban', 'pak', 'eg', 'indo']

In [ ]:
df

         country    capital     area  population
ban   bangladesh      dhaka   147570         170
pak     pakistan  islamabad   881913         240
eg         egypt      cairo  1001450         112
indo   indonesia    jakarta  1904569         277