In [ ]:
import pandas as pd

In [ ]:
dict = {
    "country":["Bangladesh", "Afghanistan", "UAE", "Oman", "Saudi Arabia"],
    "capital":["Dhaka", "Kabul", "Abu Dhabi", "Salalah", "Jedda"],
    "area":[8.516, 17.100, 3.286, 9.597, 1.221],
    "population":[147.570, 100.39, 150.45, 87.54, 120.45]
}

In [ ]:
dict

{'country': ['Bangladesh', 'Afghanistan', 'UAE', 'Oman', 'Saudi Arabia'],
 'capital': ['Dhaka', 'Kabul', 'Abu Dhabi', 'Salalah', 'Jedda'],
 'area': [8.516, 17.1, 3.286, 9.597, 1.221],
 'population': [147.57, 100.39, 150.45, 87.54, 120.45]}

In [ ]:
df = pd.DataFrame(dict)

In [ ]:
df

        country    capital    area  population
0    Bangladesh      Dhaka   8.516      147.57
1   Afghanistan      Kabul  17.100      100.39
2           UAE  Abu Dhabi   3.286      150.45
3          Oman    Salalah   9.597       87.54
4  Saudi Arabia      Jedda   1.221      120.45

In [ ]:
df.index = ["Ban", "Afg", "UAE", "Omn", "SAE"]

In [ ]:
df

          country    capital    area  population
Ban    Bangladesh      Dhaka   8.516      147.57
Afg   Afghanistan      Kabul  17.100      100.39
UAE           UAE  Abu Dhabi   3.286      150.45
Omn          Oman    Salalah   9.597       87.54
SAE  Saudi Arabia      Jedda   1.221      120.45

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Datacamp Data Science/Pythonpractise/brics.csv", index_col = 0)

In [ ]:
df1

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
df1

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
df1["country"]

BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object

In [ ]:
df1[1:4]

   country    capital    area  population
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [ ]:
df1.loc["RU"]

country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object

In [ ]:
df1.loc[["RU"]]

   country capital  area  population
RU  Russia  Moscow  17.1       143.5

In [ ]:
df1.loc[["RU", "IN", "CH"], ["capital", "country"]]

      capital country
RU     Moscow  Russia
IN  New Delhi   India
CH    Beijing   China

In [ ]:
df1.iloc[[1]]

   country capital  area  population
RU  Russia  Moscow  17.1       143.5

In [ ]:
df1.iloc[[1,2,3]]

   country    capital    area  population
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [ ]:
df.iloc[1:4]

         country    capital    area  population
Afg  Afghanistan      Kabul  17.100      100.39
UAE          UAE  Abu Dhabi   3.286      150.45
Omn         Oman    Salalah   9.597       87.54

In [ ]:
df1.iloc[1:4, 0:2]

   country    capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing

In [ ]:
df1.iloc[[1,2,3], [0,1]]

   country    capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing

In [ ]:
df1.iloc[:, [0,1]]

         country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

# **Comparison Operator**

In [ ]:
import numpy as np

In [ ]:
bmi = np.array([21.852, 20.975, 21.75, 24.747])
bmi

array([21.852, 20.975, 21.75 , 24.747])

In [ ]:
bmi > 23

array([False, False, False,  True])

In [ ]:
z = 3

if z % 2 == 0:
  print("Z is divisible by 2")
elif z % 3 == 0:
  print("Z is divisible by 3")
else:
  print("No")

Z is divisible by 3

In [ ]:
df1["area"] > 8

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
is_huge = df1["area"] > 8
df1[is_huge]

   country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

In [ ]:
data = [1,2,3,4,5]
ser = pd.Series(data)
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
data1 = {"a":1, "b":2, "c":3}
ser1 = pd.Series(data1)
ser1

a    1
b    2
c    3
dtype: int64

In [ ]:
data2 = [10, 20, 30, 40]
index = ["a", "b", "c", "d"]
ser2 = pd.Series(data2, index=index)
ser2

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
data3 = {
    "a":[10, 20, 30, 40],
    "b":["v", "f", "g", "h"],
    "c":[100, 200, 300, 400]
}
data3

{'a': [10, 20, 30, 40], 'b': ['v', 'f', 'g', 'h'], 'c': [100, 200, 300, 400]}

In [ ]:
daf = pd.DataFrame(data3)
daf

    a  b    c
0  10  v  100
1  20  f  200
2  30  g  300
3  40  h  400

In [ ]:
daf["d"] = [50, 60, 70, 80]
daf

    a  b    c   d
0  10  v  100  50
1  20  f  200  60
2  30  g  300  70
3  40  h  400  80

In [ ]:
daf.drop("c", axis = 1, inplace=True)
daf

    a  b   d
0  10  v  50
1  20  f  60
2  30  g  70
3  40  h  80

In [ ]:
df.dtypes

country        object
capital        object
area          float64
population    float64
dtype: object

In [ ]:
print("Statistical Summary: \n", daf.describe())

Statistical Summary:
                a          d
count   4.000000   4.000000
mean   25.000000  65.000000
std    12.909944  12.909944
min    10.000000  50.000000
25%    17.500000  57.500000
50%    25.000000  65.000000
75%    32.500000  72.500000
max    40.000000  80.000000

In [67]:
for val in df1:
  print(val)

country
capital
area
population