![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [77]:
# Re-run this cell 
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

# Start coding here...
# Add as many cells as you like...

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]

## Which NYC schools have the best math results?

In [78]:
eighty_percent = (80/100) * 800

print(eighty_percent)

640.0

In [79]:
best_math_schools = schools[schools["average_math"] >= eighty_percent][["school_name", "average_math"]].sort_values(by="average_math", ascending=False)

best_math_schools

                                           school_name  average_math
88                              Stuyvesant High School           754
170                       Bronx High School of Science           714
93                 Staten Island Technical High School           711
365  Queens High School for the Sciences at York Co...           701
68   High School for Mathematics, Science, and Engi...           683
280                     Brooklyn Technical High School           682
333                        Townsend Harris High School           680
174  High School of American Studies at Lehman College           669
0    New Explorations into Science, Technology and ...           657
45                       Eleanor Roosevelt High School           641

In [80]:
schools.head(1)

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN

[1 rows x 7 columns]

In [81]:
schools_1 = schools

schools_1.head()

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]

In [82]:
schools_1["total_SAT"] = schools_1[["average_math", "average_reading", 
                                    "average_writing"]].sum(axis=1)

schools_1.head(2)

                                         school_name  ... total_SAT
0  New Explorations into Science, Technology and ...  ...      1859
1                               Essex Street Academy  ...      1193

[2 rows x 8 columns]

In [83]:
top_10_schools = schools_1[["school_name", "total_SAT"]].sort_values(by="total_SAT", ascending=False).head(10)

top_10_schools

                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981
365  Queens High School for the Sciences at York Co...       1947
5                       Bard High School Early College       1914
280                     Brooklyn Technical High School       1896
45                       Eleanor Roosevelt High School       1889
68   High School for Mathematics, Science, and Engi...       1889

In [84]:
schools.head(2)

                                         school_name  ... total_SAT
0  New Explorations into Science, Technology and ...  ...      1859
1                               Essex Street Academy  ...      1193

[2 rows x 8 columns]

In [85]:
borough_states = schools_1.groupby(["borough"]).agg(num_schools=("school_name", "count"), average_SAT=("total_SAT", "mean"), std_SAT=("total_SAT", "std")).round(2)
borough_states

               num_schools  average_SAT  std_SAT
borough
Bronx                   98      1202.72   150.39
Brooklyn               109      1230.26   154.87
Manhattan               89      1340.13   230.29
Queens                  69      1345.48   195.25
Staten Island           10      1439.00   222.30

In [86]:
largest_std_dev = borough_states.sort_values(by="std_SAT", ascending=False).reset_index().head(1)

largest_std_dev

     borough  num_schools  average_SAT  std_SAT
0  Manhattan           89      1340.13   230.29